import Sidebar from "@/components/Layout/Sidebar/Sidebar";
import ThemeRegistry from "@/theme/ThemeRegistry";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body>
          <Sidebar>{children}</Sidebar>
        </body>
      </ThemeRegistry>
    </html>
  );
}
